// NOTE: DO NOT EDIT: This file is generated by update-example-data.js
angular.module('BuildJS').service('ExampleData', function(){
  return [
  {
    "id": "5ef1a5ca-2b09-499d-9076-c0545dfd624b",
    "package": {
      "name": "Sample_gulpfile.js",
      "description": "This file is just a quick sample to give you a taste of what gulp does.",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "repository": {
        "type": "git",
        "url": "https://github.com/gulpjs/gulp.git"
      },
      "homepage": "https://github.com/gulpjs/gulp",
      "devDependencies": {
        "gulp": "^3.8.0",
        "gulp-coffee": "^2.0.1",
        "gulp-concat": "^2.2.0",
        "gulp-imagemin": "^0.6.1",
        "gulp-uglify": "^0.3.0",
        "rimraf": "^2.2.8"
      }
    },
    "terms": [
      "gulp",
      "gulp-coffee",
      "gulp-concat",
      "gulp-imagemin",
      "gulp-uglify",
      "rimraf"
    ]
  },
  {
    "id": "6a1b0eab-a13a-4582-979b-629f191e6daa",
    "package": {
      "name": "build_js_site",
      "version": "0.0.0",
      "description": "This is used to build the build_js site.",
      "main": "gulpfile.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "Douglas Meyer <Douglas.Meyer@mail.com>",
      "license": "ISC",
      "devDependencies": {
        "bower": "^1.3.5",
        "connect": "^2.19.6",
        "connect-history-api-fallback": "0.0.4",
        "gulp": "^3.8.0",
        "gulp-clean": "^0.3.0",
        "gulp-concat": "^2.2.0",
        "gulp-embedlr": "^0.5.2",
        "gulp-jade": "^0.5.0",
        "gulp-livereload": "^2.1.0",
        "gulp-minify-css": "^0.3.4",
        "gulp-sass": "^0.7.2",
        "tiny-lr": "0.0.7"
      }
    },
    "terms": [
      "bower",
      "connect",
      "connect-history-api-fallback",
      "gulp",
      "gulp-clean",
      "gulp-concat",
      "gulp-embedlr",
      "gulp-jade",
      "gulp-livereload",
      "gulp-minify-css",
      "gulp-sass",
      "tiny-lr"
    ]
  }
];
});