// NOTE: DO NOT EDIT: This file is generated by update-example-data.js
angular.module('BuildJS').service('ExampleData', function(){
  return {
    "6a1b0eab-a13a-4582-979b-629f191e6daa": {
  "name": "build_js_site",
  "version": "0.0.0",
  "description": "This is used to build the build_js site.",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Douglas Meyer <Douglas.Meyer@mail.com>",
  "license": "ISC",
  "devDependencies": {
    "bower": "^1.3.5",
    "gulp": "^3.8.0",
    "gulp-clean": "^0.3.0",
    "gulp-concat": "^2.2.0",
    "gulp-embedlr": "^0.5.2",
    "gulp-jade": "^0.5.0",
    "gulp-livereload": "^2.1.0",
    "gulp-minify-css": "^0.3.4",
    "gulp-sass": "^0.7.2",
    "through": "^2.3.4",
    "tiny-lr": "0.0.7"
  }
}
  };
});